name: flutter_matrix_html
description: A Flutter widget for rendering static matrix html tags as Flutter widgets. (Will render over 70 different html tags!)
version: 0.1.6
homepage: https://github.com/Sorunome/flutter_matrix_html

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: '>=0.5.0'

dependencies:
  html: ^0.14.0
  flutter:
    sdk: flutter
  cached_network_image: any
  matrix_link_text: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
